name: CustomRecipes
version: 1.2
main: me.mehboss.recipe.Main
author: mehboss
description: An easy-to-use remastered custom recipe plugin!
commands:
  crecipe:
    description: Syntax is give [recipe] or simply reload